import time

print('Loading up - just a sec...')
time.sleep(1)
print("Elecreatures")
print("")
print(" vv      vv")
print("")
print("(S)tart (Q)uit")
print("")
print("   /\-/\\")
print("  /O V O\\")
print("  \__^__/")
print("")
response = input("Your input > ")
if response == ('q' or 'Q'):
    print('Quitting...')
    time.sleep(1)
    quit
else:
    print("Before you progress - please read the following.")
    time.sleep(2)
    print("When you choose your starter, please do not select")
    print("anything other than the selections you're given from here on out,")
    time.sleep(3)
    print("or else the game may crash.")
    time.sleep(2)
    print('')
    input("Press Enter when you are ready.")

    print('Orb (1) - Vinail, The Slime Snail Elecreature')
    print("   | Earth Type")
    print('   O   ')
    print('Orb (2) - Aquat, The Aqua Feline Elecreature')
    print('   | Aqua Type')
    print('   O')
    print('Orb (3) - Scorchain, The Scorching-Hot Canine Elecreature')
    print('   | Flame Type')
    print('   O')
    print('')
    print('Alright, young Elecreature Tamer. Your journey begins here.')
    print('')
    print('Out of three Ele-Orbs, you will pick only one for your adventure.')
    print('')
    print('Choose wisely!')
    print('')
    print('')
response = input("Your input > ")
print('Your Orb contains..')
print('')
if response == '1':
    print('Vinail - The Slime Snail Elecreature')
if response == '2':
    print('Aquat - The Aqua Feline Elecreature')
if response == '3':
    print('Scorchain - The Scorching-Hot Canine Elecreature')
print('')
if response == '1':
    print('Earth Type')
if response == '2':
    print('Aqua Type')
if response == '3':
    print('Flame Type')
print('')
if response == '1':
    print("Appearance: A green blob of slime with eyes and a snail's shell on")
    print("its back. Slimy vines appear to protrude out of its body, wrapping")
    print("itself around the shell.")
if response == '2':
    print("Appearance: A cat made of water, able to deform itself with")
    print("noticeable ease. ")
if response == '3':
    print("Appearance: A crimson-coloured dog with flames encircling it's body.")
    print("It has a loyal relationship towards its Tamer and its friends. If")
    print("it does not wish to harm anybody with its flames, it may cease the")
    print("pain that it gives off at will.")
print('')
if response == '1':
    print('     ____')
    print('    /   w\\')
    print('OwO|_w_W_w|')
    print(' WWWWWWWWWW')
    starter = 'Vinail'
if response == '2':
    print('W    W')
    print('Ww  wW -----')
    print('w0--0w -----')
    print('W----W -----')
    print(' W--W')
    print(' W--W         WWWWWW')
    print('W---WWWWWWWWWWW')
    print('W---------W')
    print('WW WW WW WW')
    starter = 'Aquat'
if response == '3':
    print('W  ^ W')
    print('Ww/^\W')
    print('w0ww0w     ^')
    print('WWWWWW    / \\')
    print(' WWWW    /  /')
    print(' WWWW  / / \ \ WWWWWW')
    print('WWWWWWWWWWWWWWW')
    print('WWWWWWWWWWW')
    print('WW WW WW WW')
    starter = 'Scorchain'
print('')
print("Good choice. The world of Elecreatures is dangerous, so be sure")
print("to always bring an Elecreature with you during your journeys!")
input('Press Enter to continue.')
print('')
print('A wild Pythorn has appeared!')
print('                         LVL7              ^^^^^')
print('                                   ^^^^   /     \\')
print('                                  / \o|  /  / \  \ /\\')
print('                              >----  ||_/  /   \  \  |')
print('                                  \_/_|   /    \   /')
print('                                      vvvv       vvv')
if starter == 'Vinail':
    print('     ____')     
    print('    /w   \ ')   
    print('   |w_W_w_|WwW LVL5')
    print('   WWWWWWWWWW ')
if starter == 'Aquat':
    print('        Ww  wW')
    print('  ----- W-WW-W -----')
    print('  ----- W----W ----- LVL5')
    print('  ----- W----W -----')
    print('         W--W')     
    print('     WWWW----W')   
    print('  WWW--------W')
    print(' W----WWWWW--W')
if starter == 'Scorchain':
    print('        W  ^  W')
    print('     ^  Ww/^\wW')
    print('   / /  WWWWWWW LVL5')
    print('  /  \  WWWWWW')
    print('  \ ^ \  WWWW')     
    print('   \ WWWWWWWWW')   
    print('  WWWWWWWWWWWW')
    print(' WWW WWWWWWWWW ')
time.sleep(2)
print('')
print('')
print('')
print('')
print('')
print('')
print('')
print('')
print('')
print('')
print('')
print('')
print('')
print('')
print('')
print('')
print('')
print('')
print('')
print('')
print('')
print('')
print('')
print('')
print('')
print('')
print('')
print('                         LVL7               ^^^^^')
print('                                    ^^^^   /     \\')
print('                                   |  0|  /  / \  \ /\\')
print('                                   --  |_/  /   \  \  |')
print('                                   |___|   /     \   /')
print('                                       vvvv       vvv')
if starter == 'Vinail':
    print('     ____')     
    print('    /w   \ ')   
    print('   |w_W_w_|WwW LVL5')
    print('   WWWWWWWWWW ')
if starter == 'Aquat':
    print('        Ww  wW')
    print('  ----- W-WW-W -----')
    print('  ----- W----W ----- LVL5')
    print('  ----- W----W -----')
    print('         W--W')     
    print('     WWWW----W')   
    print('  WWW--------W')
    print(' W----WWWWW--W')
if starter == 'Scorchain':
    print('        W  ^  W')
    print('     ^  Ww/^\wW')
    print('   / /  WWWWWWW LVL5')
    print('  /  \  WWWWWW')
    print('  \ ^ \  WWWW')     
    print('   \ WWWWWWWWW')   
    print('  WWWWWWWWWWWW')
    print(' WWW WWWWWWWWW ')
time.sleep(.5)
print('Which attack will you use?')
print('')
print('(1) Bash, damages foe')
print("(2) Scare, lowers foe's power")
print('')
response = input('Your input > ')
if response == '1':
    print('Your Elecreature *Bash*ed into the opponent!')
    print('')
    print("That must've hurt! It did some damage..")
    time.sleep(2)
    print("")
    print("The wild Pythorn fainted! You win!")
    print("")
if response == '2':
    print('Your Elecreature *Scare*d the opponent!')
    print('')
    print("That must've been really scary! It lowered the foe's power..")
    time.sleep(2)
    print("")
    print("The wild Pythorn had to *Bite* your Elecreature!")
    print("")
    print("That really hurt. It's super effective! It did some damage..")
    time.sleep(2)
    print("")
    print("Your Elecreature fainted! You lose!")
time.sleep(0.5)
input("This is the end of the test demo. Thank you for playing!")
